### ISSUE TITLE
Error Cannot read properties of undefined (reading 'conversationId') after deployment

### ISSUE THREAD

**Issue by bijunorderia** [thunderbug1/LibreChatAzureDeployment#13]
Hi,

Thanks for creating this useful addition to the already awesome Librechat.

My deployment was smooth without errors, however when I open the URL, I get the following error.

> TypeError: Cannot read properties of undefined (reading 'conversationId')
>     at https://lxxxxxx.azurewebsites.net/assets/index-kznUAxii.js:1:3826
>     at Array.reduce (<anonymous>)
>     at Pl (https://lxxxxxx.azurewebsites.net/assets/index-kznUAxii.js:1:3800)
>     at https://lxxxxxx.azurewebsites.net/assets/index-kznUAxii.js:37:77779
>     at Object.HR [as useMemo] (https://lxxxxxx.azurewebsites.net/assets/vendor-B_6jzxSQ.js:38:23931)
>     at Wt.useMemo (https://lxxxxxx.azurewebsites.net/assets/vendor-B_6jzxSQ.js:9:6208)
>     at ym (https://lxxxxxx.azurewebsites.net/assets/index-kznUAxii.js:37:77767)
>     at EE (https://lxxxxxx.azurewebsites.net/assets/vendor-B_6jzxSQ.js:38:19548)
>     at Uy (https://lxxxxxx.azurewebsites.net/assets/vendor-B_6jzxSQ.js:40:3139)
>     at gN (https://lxxxxxx.azurewebsites.net/assets/vendor-B_6jzxSQ.js:40:44833)

I have used the default CosmosDB configuration, do I need to do something to populate the DB with a schema??

**Comment by thunderbug1** [comment]
No there shouldn't be any init steps necessary.
To me it looks like an error that is cause by a newer version of librechat, can you please open an issue there?

**Comment by ottodeng** [comment]
same encounter this issue.

**Comment by bijunorderia** [comment]
I found an alternate repo which works. 
https://github.com/Pwd9000-ML/terraform-azurerm-openai-private-chatgpt

**Comment by PedroGruvhagen** [comment]
@bijunorderia perfect, many thanks!
